CREATE TABLE `addresses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('shipping','billing') NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`company` varchar(255),
	`address1` varchar(255) NOT NULL,
	`address2` varchar(255),
	`city` varchar(100) NOT NULL,
	`state` varchar(100) NOT NULL,
	`zipCode` varchar(20) NOT NULL,
	`country` varchar(100) NOT NULL DEFAULT 'United States',
	`phone` varchar(20),
	`isDefault` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `addresses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cartItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(255),
	`productId` int NOT NULL,
	`variantId` int,
	`quantity` int NOT NULL DEFAULT 1,
	`isSubscription` boolean DEFAULT false,
	`subscriptionPlanId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cartItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `discountCodes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`description` text,
	`discountType` enum('percentage','fixed') NOT NULL,
	`discountValue` int NOT NULL,
	`minPurchaseInCents` int DEFAULT 0,
	`maxUsesTotal` int,
	`maxUsesPerCustomer` int DEFAULT 1,
	`usedCount` int DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`startsAt` timestamp,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `discountCodes_id` PRIMARY KEY(`id`),
	CONSTRAINT `discountCodes_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `orderItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`productId` int NOT NULL,
	`variantId` int,
	`productName` varchar(255) NOT NULL,
	`variantName` varchar(255),
	`sku` varchar(100),
	`quantity` int NOT NULL,
	`priceInCents` int NOT NULL,
	`totalInCents` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `orderItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(50) NOT NULL,
	`userId` int,
	`email` varchar(320) NOT NULL,
	`status` enum('pending','processing','shipped','delivered','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`subtotalInCents` int NOT NULL,
	`shippingInCents` int NOT NULL DEFAULT 0,
	`taxInCents` int NOT NULL DEFAULT 0,
	`discountInCents` int NOT NULL DEFAULT 0,
	`totalInCents` int NOT NULL,
	`shippingFirstName` varchar(100) NOT NULL,
	`shippingLastName` varchar(100) NOT NULL,
	`shippingAddress1` varchar(255) NOT NULL,
	`shippingAddress2` varchar(255),
	`shippingCity` varchar(100) NOT NULL,
	`shippingState` varchar(100) NOT NULL,
	`shippingZipCode` varchar(20) NOT NULL,
	`shippingCountry` varchar(100) NOT NULL,
	`shippingPhone` varchar(20),
	`billingFirstName` varchar(100) NOT NULL,
	`billingLastName` varchar(100) NOT NULL,
	`billingAddress1` varchar(255) NOT NULL,
	`billingAddress2` varchar(255),
	`billingCity` varchar(100) NOT NULL,
	`billingState` varchar(100) NOT NULL,
	`billingZipCode` varchar(20) NOT NULL,
	`billingCountry` varchar(100) NOT NULL,
	`paymentMethod` varchar(50),
	`paymentStatus` enum('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',
	`transactionId` varchar(255),
	`trackingNumber` varchar(255),
	`shippingCarrier` varchar(100),
	`customerNotes` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`paidAt` timestamp,
	`shippedAt` timestamp,
	`deliveredAt` timestamp,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `productVariants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`sku` varchar(100),
	`priceInCents` int NOT NULL,
	`compareAtPriceInCents` int,
	`stockQuantity` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `productVariants_id` PRIMARY KEY(`id`),
	CONSTRAINT `productVariants_sku_unique` UNIQUE(`sku`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`longDescription` text,
	`priceInCents` int NOT NULL,
	`compareAtPriceInCents` int,
	`sku` varchar(100),
	`stockQuantity` int NOT NULL DEFAULT 0,
	`lowStockThreshold` int DEFAULT 10,
	`imageUrl` varchar(500),
	`galleryImages` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`servingSize` varchar(100),
	`servingsPerContainer` int,
	`ingredients` text,
	`supplementFacts` text,
	`warnings` text,
	`directions` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_slug_unique` UNIQUE(`slug`),
	CONSTRAINT `products_sku_unique` UNIQUE(`sku`)
);
--> statement-breakpoint
CREATE TABLE `subscriptionPlans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`intervalType` enum('monthly','quarterly','annual') NOT NULL,
	`intervalCount` int NOT NULL DEFAULT 1,
	`discountPercentage` int DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscriptionPlans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`planId` int NOT NULL,
	`productId` int NOT NULL,
	`variantId` int,
	`status` enum('active','paused','cancelled','expired') NOT NULL DEFAULT 'active',
	`quantity` int NOT NULL DEFAULT 1,
	`priceInCents` int NOT NULL,
	`nextBillingDate` timestamp NOT NULL,
	`lastBillingDate` timestamp,
	`cancelledAt` timestamp,
	`pausedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscriptions_id` PRIMARY KEY(`id`)
);
