CREATE TABLE `postPurchaseEmails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`userId` int,
	`email` varchar(320) NOT NULL,
	`productId` int NOT NULL,
	`purchaseDate` timestamp NOT NULL,
	`day7EmailSentAt` timestamp,
	`day21EmailSentAt` timestamp,
	`day60EmailSentAt` timestamp,
	`day90EmailSentAt` timestamp,
	`hasReordered` boolean DEFAULT false,
	`reorderDate` timestamp,
	`reorderOrderId` int,
	`hasSubscribed` boolean DEFAULT false,
	`subscribedAt` timestamp,
	`hasReviewed` boolean DEFAULT false,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `postPurchaseEmails_id` PRIMARY KEY(`id`)
);
